Revert "selftests/exec: create dependencies from C not Makefile"
This reverts commit 333354b126e4db3526dad0731fb0b554a86bec9b.

diff --git a/tools/testing/selftests/exec/Makefile b/tools/testing/selftests/exec/Makefile
--- a/tools/testing/selftests/exec/Makefile
+++ b/tools/testing/selftests/exec/Makefile
@@ -1,9 +1,28 @@
-CFLAGS += -Wall
+CFLAGS = -Wall
+BINARIES = execveat
+DEPS = execveat.symlink execveat.denatured script
+all: $(BINARIES) $(DEPS)
+
+subdir:
+	mkdir -p $@
+script:
+	echo '#!/bin/sh' > $@
+	echo 'exit $$*' >> $@
+	chmod +x $@
+execveat.symlink: execveat
+	ln -s -f $< $@
+execveat.denatured: execveat
+	cp $< $@
+	chmod -x $@
+%: %.c
+	$(CC) $(CFLAGS) -o $@ $^
+
 TEST_PROGS := execveat
-CREATED = subdir subdir.moved execveat.symlink exeveat.moved execveat.denatured script non-script
-all: $(TEST_PROGS)
+TEST_FILES := $(DEPS)
 
 include ../lib.mk
 
+override EMIT_TESTS := echo "mkdir -p subdir; (./execveat && echo \"selftests: execveat [PASS]\") || echo \"selftests: execveat [FAIL]\""
+
 clean:
-	rm -rf $(TEST_PROGS) $(CREATED) xxxxx* *.ephemeral
+	rm -rf $(BINARIES) $(DEPS) subdir.moved execveat.moved xxxxx*
